
steps:
- name: 'gcr.io/cloud-builders/go'
  args: ['install', '-a', '-ldflags', "'-s'", '-installsuffix', 'cgo', 'github.com/sinmetal/pinger']
  env: [
    'PROJECT_ROOT=github.com/sinmetal/pinger',
    'CGO_ENABLED=0',
    'GOOS=linux'
  ]
- name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "gcr.io/$PROJECT_ID/sinmetal/pinger", "."]
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/sinmetal/pinger"]
images: ['gcr.io/$PROJECT_ID/sinmetal/pinger']